// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Courses_Project.Models;

public partial class CoursesDBContext : DbContext
{
    public CoursesDBContext()
    {
    }

    public CoursesDBContext(DbContextOptions<CoursesDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}