// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_WF.Models;

public partial class Department
{
    public int ID { get; set; }

    public string Dept_Name { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}